# --- File Paths ---
# NOTE: Update data_directory path for HPC deployment
data_directory: "/home/rylan/Documents/research/NASA/programDirectory/data/"
output_directory: "/home/rylan/Documents/NASA/cloudML/programDirectory/plots/"

# --- Experiment Parameters ---
pretrain_flight: "30Oct24"
overweight_flight: "30Oct24"
overweight_factor: 3.5
validation_flight: "12Feb25" # Flight to use for validation set

# --- Training Parameters ---
learning_rate: 0.001
weight_decay: 0.04
epochs: 1 # Increased epochs for more training with attention
optimizer: "AdamW"
scheduler: "ReduceLROnPlateau"
temporal_frames: 3
loss_type: "huber" # Use weighted huber mae loss
loss_alpha: 0.5 # Not needed for simplified Huber loss
early_stopping_patience: 10 # Increased patience for longer training with attention
filter_type: "basic"
early_stopping_min_delta: 0.00025
huber_delta: 1.0
gamma: 1.5
under_weight: 1.0
loo: true
loo_epochs: 1
batch_size: 8
warmup_steps: 2000
hard_mining_k: 0.35
hard_mining_factor: 1.5
swath_slice: [40, 480]
hpc_mode: false

# --- Flight Information ---
flights:
  - name: "10Feb25"
    iFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/10Feb25/GLOVE2025_IRAI_L1B_Rev-_20250210-003.h5"
    cFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/10Feb25/CPL_L2_V1-02_01kmLay_259015_10feb25.hdf5"
    nFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/10Feb25/CRS_20250210_nav.hdf"
  - name: "30Oct24"
    iFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/30Oct24/WHYMSIE2024_IRAI_L1B_Rev-_20241030-008.h5"
    cFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/30Oct24/CPL_L2_V1-02_01kmLay_259006_30oct24.hdf5"
    nFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/30Oct24/CRS_20241030_nav.hdf"
  - name: "23Oct24"
    iFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/23Oct24/WHYMSIE2024_IRAI_L1B_Rev-_20241023-007.h5"
    cFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/23Oct24/CPL_L2_V1-02_01kmLay_259004_23oct24.hdf5"
    nFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/23Oct24/CRS_20241023_nav.hdf"
  - name: "18Feb25"
    iFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/18Feb25/GLOVE2025_IRAI_L1B_Rev-_20250218-002.h5"
    cFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/18Feb25/CPL_L2_V1-02_01kmLay_259017_18feb25.hdf5"
    nFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/18Feb25/CRS_20250218_nav.hdf"
  - name: "12Feb25"
    iFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/12Feb25/GLOVE2025_IRAI_L1B_Rev-_20250212-005.h5"
    cFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/12Feb25/CPL_L2_V1-02_01kmLay_259016_12feb25.hdf5"
    nFileName: "/home/rylan/Documents/research/NASA/programDirectory/data/12Feb25/CRS_20250212_nav.hdf"
